### ISSUE TITLE
ssh key based login

### ISSUE THREAD

**Issue by weberjn** [pschweitz/DBITail#1]
Please add support for ssh key based login to access the log files.

http://stackoverflow.com/questions/4932005/can-we-use-jsch-for-ssh-key-based-communication

**Comment by pschweitz** [comment]
Ok I will think on that soon

Thanks for you contribution
Phil

**Comment by pschweitz** [comment]
Hi 
I added support for SSH key authentication.

Cheers
Philippe

**Comment by weberjn** [comment]
Thanks, works perfect.

Juergen
