### ISSUE TITLE
ssh sudo and additional commands 

### ISSUE THREAD

**Issue by kotso02** [pschweitz/DBITail#3]
Hi Philippe, i've got dbi tail ..very helpful and has a lot of potentiality..can you please add additional commands to authenticate via ssh..like su and other commands ...cos we normally have to su to tail logs..which requires special command to switch to root.Appreciate it..Thanks!

**Comment by pschweitz** [comment]
Hi,

Thanks for looking at dbi Tail !

Have you tried to put required commands into your bash_profile or bashrc ?
I have got same issue by a customer and this solution is working well.

Best regards
Philippe

**Comment by kotso02** [comment]
Thanks for your response Phillippe...I tried your solution..but i will have
to type the password once i put the command in .bashrc...dbtail shell is
not interactive..any other suggestions..?
Thanks,
Solomon

**Comment by pschweitz** [comment]
Maybe you can configure your sudo to accept the login without password just for your account ?

http://apple.stackexchange.com/questions/82438/allow-sudo-to-another-user-without-password
http://mindspill.net/computing/linux-notes/su-as-another-user-without-password/

Philippe

**Comment by kotso02** [comment]
Thanks for the quick response, Phillipe! we normally run a different
command as opposed to su or sudo..and technically enabling a login without
a password will be a huge security violation..any other suggestions?

Thanks,
Solomon

**Comment by pschweitz** [comment]
Hi Solomon,

Yes I understand your concern.

I am unfortunately not thinking adding an interactive input to the dbi Tail. In fact this will change the nature of the tool which is not intended to replace a shell client like putty.

The suggestions I can propose you are following:
- Still try to configure the server side with an enterprise level security layer integration (I know it is possible for sudo or equiv.)
- Fork the project and add the specific features you need.
- Eventually contact dbi services or another company to schedule a particular development for you.
 
But thank you for your contribution anyway !

Cheers,
Philippe

**Comment by kotso02** [comment]
Appreciate it, Phillipe!... thanks for being responsive..
Thanks
Solomon
