### ISSUE TITLE
Multiple Hosts into One Screen

### ISSUE THREAD

**Issue by purpledogeatsgreenpoop** [pschweitz/DBITail#4]
I thought I remember somewhere reading that with DBITail it was possible to merge multiple hosts into once screen (tab) instead of having to flip back and forth between tabs.  Am I missing something or is it just not possible?

Thank you!!!

**Comment by pschweitz** [comment]
Hi,

It is something unfortunately not available at the moment, but yes this feature is something I have in mind for some time...

I will let you know when it will be available.

Philippe
