### ISSUE TITLE
SHH Connections with non-standard ports?

### ISSUE THREAD

**Issue by psyferre** [pschweitz/DBITail#5]
Is it possible to specify the port number for SSH connections?  For example: `ssh://user@216.12.255.255:22187:/var/log/apache2/error.log` naturally fails to connect, but I can't think of an alternative way to specify the port.

Fantastic application, btw!  It works great if the port is standard. :)

**Comment by pschweitz** [comment]
Hi,

The change has been implemented in the renamed tool repository:
https://github.com/pschweitz/insidelog

enjoy ;)
